#!/usr/bin/env python3
"""Column-level lineage tracer for the portifolio dbt project.

Traces a target model column back through the dbt DAG to its raw sources,
using sqlglot to parse each model's *compiled* SQL (ref()/source() already
resolved to real relation names) and dbt's manifest.json to hop from one
model to its parents.

Requires a manifest with `compiled_code` populated, i.e. generated by
`dbt compile` / `dbt build` / `dbt run` — NOT `dbt parse` (which only
discovers the DAG shape, without rendering SQL).

Usage:
    python column_lineage.py mart_api_health service
    python column_lineage.py mart_api_health service --json
    python column_lineage.py mart_api_health service --manifest ../target/manifest.json
"""
from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from sqlglot import exp
from sqlglot.errors import SqlglotError
from sqlglot.lineage import lineage as sqlglot_lineage

DEFAULT_MANIFEST = Path(__file__).resolve().parents[1] / "target" / "manifest.json"
DEFAULT_DIALECT = "postgres"
MAX_DEPTH = 15


@dataclass
class LineageNode:
    """One hop in a column's ancestry."""

    node: str  # dbt unique_id, or a raw relation key when unresolved
    column: str
    reason: Optional[str] = None  # set only for terminal/unresolved leaves
    children: list["LineageNode"] = field(default_factory=list)

    @property
    def is_leaf(self) -> bool:
        return not self.children

    def to_dict(self) -> dict:
        d = {"node": self.node, "column": self.column}
        if self.reason:
            d["reason"] = self.reason
        if self.children:
            d["children"] = [c.to_dict() for c in self.children]
        return d


class ManifestGraph:
    """Lookups over manifest.json needed to hop across the dbt DAG."""

    def __init__(self, manifest_path: Path):
        with open(manifest_path) as f:
            manifest = json.load(f)
        self.nodes: dict = manifest["nodes"]
        self.sources: dict = manifest["sources"]
        self._relation_to_id = self._build_relation_index()

    def _build_relation_index(self) -> dict[str, str]:
        index: dict[str, str] = {}
        for unique_id, source in self.sources.items():
            key = _relation_key(source.get("database"), source.get("schema"), source.get("identifier"))
            index[key] = unique_id
        for unique_id, node in self.nodes.items():
            identifier = node.get("alias") or node.get("name")
            key = _relation_key(node.get("database"), node.get("schema"), identifier)
            index[key] = unique_id
        return index

    def is_source(self, unique_id: str) -> bool:
        return unique_id in self.sources

    def compiled_sql(self, unique_id: str) -> Optional[str]:
        node = self.nodes.get(unique_id)
        return node.get("compiled_code") if node else None

    def resolve_relation(self, database: Optional[str], schema: Optional[str], name: Optional[str]) -> Optional[str]:
        return self._relation_to_id.get(_relation_key(database, schema, name))

    def display(self, unique_id: str) -> str:
        if unique_id in self.sources:
            source = self.sources[unique_id]
            return f"source:{source.get('source_name')}.{source.get('name')}"
        node = self.nodes.get(unique_id)
        if not node:
            return unique_id
        return f"{node.get('resource_type', 'model')}:{node.get('name', unique_id)}"


def _relation_key(database: Optional[str], schema: Optional[str], name: Optional[str]) -> str:
    return f"{database}.{schema}.{name}".lower()


def _bare_column_name(qualified_name: str) -> str:
    """sqlglot lineage node names look like '\"alias\".\"col\"' — take the last part."""
    return qualified_name.rsplit(".", 1)[-1].strip('"`\'')


def trace_column(
    graph: ManifestGraph,
    unique_id: str,
    column: str,
    dialect: str = DEFAULT_DIALECT,
    depth: int = 0,
    _seen: Optional[set[tuple[str, str]]] = None,
) -> LineageNode:
    """Recursively resolve `column`'s ancestry starting at dbt node `unique_id`."""
    seen = _seen if _seen is not None else set()
    edge = (unique_id, column)

    if depth > MAX_DEPTH:
        return LineageNode(unique_id, column, reason="max-depth-exceeded")
    if edge in seen:
        return LineageNode(unique_id, column, reason="cycle-detected")
    seen.add(edge)

    if graph.is_source(unique_id):
        return LineageNode(unique_id, column, reason="raw-source")

    sql = graph.compiled_sql(unique_id)
    if not sql:
        return LineageNode(unique_id, column, reason="no-compiled-sql (run `dbt compile`)")

    try:
        root = sqlglot_lineage(column, sql, dialect=dialect)
    except SqlglotError as e:
        return LineageNode(unique_id, column, reason=f"sqlglot-parse-error: {e}")

    result = LineageNode(unique_id, column)
    for leaf in _leaves(root):
        if leaf is root:
            # The column had no traceable FROM source (e.g. a literal/constant).
            continue

        table = leaf.expression if isinstance(leaf.expression, exp.Table) else None
        if table is None:
            result.children.append(LineageNode(unique_id, column, reason="non-table-expression (literal/computed)"))
            continue

        leaf_column = _bare_column_name(leaf.name)
        parent_id = graph.resolve_relation(table.catalog or None, table.db or None, table.name)
        if parent_id is None:
            raw_relation = ".".join(p for p in (table.catalog, table.db, table.name) if p)
            result.children.append(LineageNode(raw_relation, leaf_column, reason="relation-not-in-manifest"))
            continue

        result.children.append(trace_column(graph, parent_id, leaf_column, dialect, depth + 1, seen))

    if not result.children:
        result.reason = "terminal-select (no upstream columns found)"

    return result


def _leaves(node) -> list:
    if not node.downstream:
        return [node]
    found = []
    for child in node.downstream:
        found.extend(_leaves(child))
    return found


def format_tree(node: LineageNode, graph: ManifestGraph, depth: int = 0) -> str:
    label = node.node if node.reason == "relation-not-in-manifest" else graph.display(node.node)
    connector = "└─ " if depth > 0 else ""
    line = f"{'   ' * depth}{connector}{label}.{node.column}"
    if node.reason:
        line += f"  [{node.reason}]"
    lines = [line]
    for child in node.children:
        lines.append(format_tree(child, graph, depth + 1))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("model", help="dbt model name (as declared in the manifest, e.g. mart_api_health)")
    parser.add_argument("column", help="column name to trace")
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST, help="path to manifest.json")
    parser.add_argument("--dialect", default=DEFAULT_DIALECT, help="sqlglot SQL dialect (default: postgres)")
    parser.add_argument("--json", action="store_true", help="output machine-readable JSON instead of a tree")
    args = parser.parse_args()

    if not args.manifest.exists():
        print(f"error: manifest not found at {args.manifest} (run `dbt compile` first)", file=sys.stderr)
        return 1

    graph = ManifestGraph(args.manifest)
    unique_id = next(
        (uid for uid, n in graph.nodes.items() if n.get("name") == args.model and uid.startswith("model.")),
        None,
    )
    if unique_id is None:
        print(f"error: model '{args.model}' not found in manifest", file=sys.stderr)
        return 1

    result = trace_column(graph, unique_id, args.column, dialect=args.dialect)

    if args.json:
        print(json.dumps(result.to_dict(), indent=2))
    else:
        print(format_tree(result, graph))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
