
name: 'portfolio'
version: '1.0.0'

profile: 'portfolio'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  portfolio:
    staging:
      +materialized: view
      +tags: [staging]
      varejo:
        +schema: staging_varejo
        +tags: [staging, varejo]
      biblioteca:
        +schema: staging_biblioteca
        +tags: [staging, biblioteca]
      rede_social:
        +schema: staging_rede_social
        +tags: [staging, rede_social]
      system:
        +schema: staging_system
        +tags: [staging, system]
    intermediate:
      +materialized: view
      varejo:
        +schema: intermediate_varejo
        +tags: [intermediate, varejo]
      biblioteca:
        +schema: intermediate_biblioteca
        +tags: [intermediate, biblioteca]
      rede_social:
        +schema: intermediate_rede_social
        +tags: [intermediate, rede_social]
      system:
        +schema: intermediate_system
        +tags: [intermediate, system]
    mart:
      +materialized: table
      varejo:
        +schema: analytics_varejo
        +tags: [mart, varejo]
        fct_vendas:
          +on_schema_change: append_new_columns
          +materialized: incremental
      biblioteca:
        +schema: analytics_biblioteca
        +tags: [mart, biblioteca]
        fct_emprestimos:
          +on_schema_change: append_new_columns
          +materialized: incremental
      rede_social:
        +schema: analytics_rede_social
        +tags: [mart, rede_social]
      system:
        +schema: analytics_system
        +tags: [mart, system]

